service: todo-service

plugins:
  - serverless-offline
  - serverless-webpack
  - serverless-dynamodb-local

custom: 
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  dynamodb:
    stages:
      - local
      - dev
    start:
      port: 8000
      inMemory: true
      migrate: true

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1

functions:
  todo-create:
    handler: src/functions/todos/create.handle
    events:
      - http:
          path: /todos/{userId}
          method: POST
          cors: true
  todo-list:
    handler: src/functions/todos/list.handle
    events:
      - http:
          path: /todos/{userId}
          method: GET
          cors: true

resources:
  Resources:
    dbUsersTodos:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: users_todos
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

